module Skelpls where

-- Haskell module generated by the BNF converter

import Abspls
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transExpr :: Expr -> Result
transExpr x = case x of
  Add expr1 expr2  -> failure x
  Mul expr1 expr2  -> failure x
  Ite expr1 expr2 expr3  -> failure x
  Val n  -> failure x



